### ISSUE TITLE
Unable to install Control Center

### ISSUE THREAD

**Issue by naviens** [control-center/serviced#1652]
i am unable to setup serviced using the readme file or using http://controlcenter.io/gettingstarted.html

Issue 
sudo apt-get update fails to fetch http://get.controlcenter.io/apt/ubuntu
http://jenkins.zendev.org/view/Control%20Center/job/serviced-build/ is not reachable for manual installation.

**Comment by wplu** [comment]
We'll get the instructions changed on http://controlcenter.io/gettingstarted.html

The README is being updated to replace the jenkins url with apt get
