### ISSUE TITLE
How can I install a new SSL certificate

### ISSUE THREAD

**Issue by jregovic** [control-center/serviced#1723]
Specifying SERVICED_KEY_FILE  and SERVICED_CERT_FILE in /etc/default/serviced does not result in the new certificate in being offered by Control Center on login. Is this the way to change the certificate?

**Comment by iancmcc** [comment]
Did you restart serviced afterward?

**Comment by alapidas** [comment]
A bug has been opened on this topic:
https://jira.zenoss.com/browse/CC-1110
