### ISSUE TITLE
docker 1.6

### ISSUE THREAD

**Issue by jpscharf** [control-center/serviced#1753]
When installing serviced it attempts to uninstall docker ```1.6.3``` and replace it with ```1.5.0```. Is 1.5 a hard dependency, or can the pkg be changed to allow 1.5+?

**Comment by alapidas** [comment]
Unfortunately it's a hard dependency on certain versions of serviced.

**Comment by wplu** [comment]
serviced 1.1 will depend on docker 1.6.x or later (TBD)
